title: PaperBold Themetitle: Ansh Aroratitle: Hellotitle: Ansh Arora

description: A clean and modern Jekyll theme

baseurl: ""email: your-email@example.com

url: "https://ansharora04.github.io"

description: >-baseurl: ""email: ansh.aro@outlook.com

# Build settings

markdown: kramdown  Write an awesome description for your new site here.

theme: jekyll-theme-minimal

plugins:baseurl: ""url: "https://ansharora04.github.io"description: Mathematics, Statistics, and Finance Research

  - jekyll-feed

  - jekyll-seo-tagurl: "https://ansharora04.github.io"baseurl: "" 

url: "https://ansharora04.github.io"

# Build settingsdomain: "ansharora04.github.io"

markdown: kramdown

remote_theme: nekosheen/PaperBold# Author Settings

plugins:author:

  - jekyll-feed  name: Ansh Arora

  - jekyll-remote-theme  bio: Mathematician and Researcher in Statistics and Finance
  occupation: Research Scholar
  email: ansh.aro@outlook.com
  github_username: AnshArora04
  avatar: /assets/images/avatar.jpg
  location: Your Location

# Build settings
remote_theme: brennanbrown/paperbold
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

# PaperBold Theme Settings
header_pages:
  - index.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - contact.md

# Collections
collections:
  research:
    output: true
    permalink: /research/:path/
  publications:
    output: true
    permalink: /publications/:path/

# Pagination
paginate: 5
paginate_path: "/page/:num"

# PaperBold Customization
accent_color: "#0066FF"
accent_color_dark: "#0044CC"
background_color: "#ffffff"
text_color: "#1A1A1A"
hero_gradient_start: "#E5F0FF"
hero_gradient_end: "#ffffff"

# Social Links
social:
  - platform: github
    url: https://github.com/AnshArora04
  - platform: google_scholar
    url: # Add your Google Scholar URL
  - platform: linkedin
    url: # Add your LinkedIn URL
  - platform: twitter
    url: # Add your Twitter URL

# Analytics (optional)
google_analytics: # Add your Google Analytics ID